name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * SUN"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
          plugin_languages: yes
          plugin_languages_ignored: html                               # List of languages to ignore
          plugin_languages_skipped: obsidian-tua_mascot-v2             # List of repositories to skip
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 3%                               # Hides all languages less than 3%

           
