name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS }}
       - uses: lowlighter/metrics@latest
         with:
            # ... other options
            plugin_languages: yes
            plugin_languages_ignored: html, css                          # List of languages to ignore
            plugin_languages_skipped: my-test-repo                       # List of repositories to skip
            plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
            plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
            plugin_languages_threshold: 2%                               # Hides all languages less than 2%
